# Generated by Django 4.0.3 on 2022-03-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('address2', models.CharField(max_length=50, verbose_name='Address2')),
                ('country', models.CharField(max_length=50, verbose_name='Couuntry')),
                ('zipp', models.CharField(max_length=50, verbose_name='Zip')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
