# Generated by Django 4.0.3 on 2022-03-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lastname'),
        ),
    ]
